name       : libluv
version    : 1.44.2.1
release    : 6
source     :
    - https://github.com/luvit/luv/releases/download/1.44.2-1/luv-1.44.2-1.tar.gz : 3eb5c7bc44f61fbc4148ea30e3221d410263e0ffa285672851fc19debf9e5c30
license    : Apache-2.0
component  : programming
summary    : Bare libuv bindings for lua
description: |
    Makes libuv available to lua scripts. It was made for the luvit project but should usable from nearly any lua project.
builddeps  :
    - pkgconfig(libuv)
    - pkgconfig(luajit)
setup      : |
    %cmake_ninja \
      -DBUILD_MODULE=OFF \
      -DBUILD_SHARED_LIBS=ON \
      -DLUA_BUILD_TYPE=System \
      -DWITH_SHARED_LIBUV=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
