name       : libluv
version    : 1.43.0
release    : 5
source     :
    - https://github.com/luvit/luv/releases/download/1.43.0-0/luv-1.43.0-0.tar.gz : 567a6f3dcdcf8a9b54ddc57ffef89d1e950d72832b85ee81c8c83a9d4e0e9de2
license    : Apache-2.0
component  : programming
summary    : Bare libuv bindings for lua
description: |
    Makes libuv available to lua scripts. It was made for the luvit project but should usable from nearly any lua project.
builddeps  :
    - pkgconfig(libuv)
    - pkgconfig(luajit)
setup      : |
    %cmake_ninja \
      -DBUILD_MODULE=OFF \
      -DBUILD_SHARED_LIBS=ON \
      -DLUA_BUILD_TYPE=System \
      -DWITH_SHARED_LIBUV=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
