name       : libluv
version    : 1.42.0_1
release    : 4
source     :
    - https://github.com/luvit/luv/releases/download/1.42.0-1/luv-1.42.0-1.tar.gz : 4b6fbaa89d2420edf6070ad9e522993e132bd7eb2540ff754c2b9f1497744db2
license    : Apache-2.0
component  : programming
summary    : Bare libuv bindings for lua
description: |
    Makes libuv available to lua scripts. It was made for the luvit project but should usable from nearly any lua project.
builddeps  :
    - pkgconfig(libuv)
    - pkgconfig(luajit)
setup      : |
    %cmake_ninja \
      -DBUILD_MODULE=OFF \
      -DBUILD_SHARED_LIBS=ON \
      -DLUA_BUILD_TYPE=System \
      -DWITH_SHARED_LIBUV=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
