name       : libluv
version    : 1.32.0
release    : 1
source     :
    - https://github.com/luvit/luv/releases/download/1.32.0-0/luv-1.32.0-0.tar.gz : 25a34b2aecf02d1fd32352c855577dcecd20c756dee9eb7ebecd206bf1de26d3
license    : Apache-2.0
component  : programming
summary    : Bare libuv bindings for lua
description: |
    Makes libuv available to lua scripts. It was made for the luvit project but should usable from nearly any lua project.
builddeps  :
    - pkgconfig(libuv)
    - pkgconfig(luajit)
setup      : |
    %cmake_ninja \
      -DBUILD_MODULE=OFF \
      -DBUILD_SHARED_LIBS=ON \
      -DLUA_BUILD_TYPE=System \
      -DWITH_SHARED_LIBUV=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
